/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MyClass<String> myclass = new MyClass<>();
        myclass.set("hello");
        String s = myclass.get();
        System.out.println(s);
    }
}
